import { photos } from '@/data/photography'
import { site, faqs, zones } from '@/data/site'
import { Motion } from './PremiumMotion'
import type { ReactNode } from 'react'

export const contactHref = site.tel.startsWith('mailto:') ? site.tel : `tel:${site.tel}`
export const contactLabel = site.tel.startsWith('mailto:') ? 'Richiedi assistenza' : site.phone
export function CTA({ label = contactLabel, secondary = false }: { label?: string; secondary?: boolean }) { return <a className={`btn${secondary ? ' secondary' : ''}`} href={contactHref}>{label}<span className="arrow" aria-hidden="true">↗</span></a> }
export function Header() { return <div className="wrap"><header className="site-header"><a className="brand" href="/" aria-label={`${site.name} — home`}><span className="brand-symbol" aria-hidden="true">R</span><span><strong>Ravenna</strong><small>Soccorso stradale</small></span></a><nav className="desktop-nav" aria-label="Navigazione principale"><a href="/#servizi">Servizi</a><a href="/#metodo">Il metodo</a><a href="/#territorio">Territorio</a><a href="/#contatti">Contatti</a></nav><div className="header-action"><CTA /></div><details className="mobile-menu"><summary>Menu +</summary><nav aria-label="Menu mobile"><a href="/#servizi">Servizi</a><a href="/#metodo">Il metodo</a><a href="/#territorio">Territorio</a><a href="/#faq">Domande frequenti</a><a href={contactHref}>{contactLabel}</a></nav></details></header></div> }
export function Shell({ children }: { children: ReactNode }) { return <div className="atelier ravenna"><a href="#contenuto" className="skip">Vai al contenuto</a><Motion /><Header />{children}<a href={contactHref} className="mobile-contact btn">{contactLabel}<span aria-hidden="true">↗</span></a></div> }
export function Marquee({ words }: { words: string[] }) { return <div className="marquee" aria-hidden="true"><div className="marquee-track">{[0, 1].map(n => <span key={n}>{words.map(word => <span key={word}>{word}<b>✳</b></span>)}</span>)}</div></div> }
export function Process() { return <section id="metodo" className="section process-section"><div className="wrap"><div className="section-top" data-reveal><div><span className="eyebrow">Il filo che lega ogni intervento</span><h2>Dall’imprevisto, alla soluzione.</h2></div><p>Un contatto diretto. Un intervento preparato. Una destinazione condivisa. Per ritrovare tranquillità, un passaggio alla volta.</p></div><div className="process">{[
  ['01', 'La tua posizione.', 'Condividi il punto esatto, il tipo di veicolo e ciò che è successo. Sono le informazioni da cui partiamo.'],
  ['02', 'Il recupero adatto.', 'Valutiamo accessi, condizioni e necessità del mezzo. Ti indichiamo modalità e costi prima di confermare.'],
  ['03', 'La tua destinazione.', 'Officina, carrozzeria o un indirizzo concordato: il trasporto si conclude nel luogo che abbiamo definito insieme.'],
].map(([n, title, text]) => <article data-reveal key={n}><span className="step">{n} /</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section> }
export function Coverage() { return <section id="territorio" className="section coverage-section"><div className="wrap coverage"><div data-reveal><span className="eyebrow">Romagna / Italia</span><h2>La città. La costa. La tua strada.</h2><p>Ravenna, i lidi e i comuni vicini: un territorio con percorsi diversi. Indica la località e un riferimento per organizzare il recupero.</p><p style={{ marginTop: 20 }}>Disponibilità e tempi vengono confermati in base alla posizione e alle condizioni dell’intervento.</p></div><nav className="zone-list" aria-label="Zone servite" data-reveal>{zones.map(zone => <a key={zone.slug} href={`/zone/${zone.slug}/`}>{zone.name}<span aria-hidden="true">↗</span></a>)}</nav></div></section> }
export function FAQ() { return <section id="faq" className="section"><div className="wrap faq-wrap"><div data-reveal><span className="eyebrow">Prima di partire</span><h2>Risposte,<br />senza dubbi.</h2></div><div className="faq-list" data-reveal>{faqs.map(faq => <details key={faq.question}><summary>{faq.question}</summary><p>{faq.answer}</p></details>)}</div></div></section> }
export function Footer() { return <><section id="contatti" className="contact"><div className="wrap" data-reveal><div><span className="eyebrow">Carroattrezzi {site.city}</span><h2>Il prossimo passo, insieme.</h2></div><CTA /></div></section><footer className="footer wrap"><div className="footer-top"><div><a className="brand" href="/"><span className="brand-symbol" aria-hidden="true">R</span><span><strong>Ravenna</strong><small>Soccorso stradale</small></span></a></div><div><p>{site.address}</p><a className="email text-link" href={`mailto:${site.email}`}>{site.email}</a></div><div><p>Soccorso e trasporto veicoli</p><p>{site.city} e provincia</p></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} {site.name}</span><span>Auto · Moto · Veicoli commerciali</span><a href="/#faq">Informazioni sul servizio</a></div></footer></> }
export function StructuredData() { const data = { '@context': 'https://schema.org', '@type': 'AutomotiveBusiness', name: site.name, url: `https://${site.domain}/`, image: `https://${site.domain}${photos.hero.src}`, description: site.description, email: site.email, ...(!site.tel.startsWith('mailto:') ? { telephone: `+39${site.tel}` } : {}), areaServed: zones.map(zone => ({ '@type': 'City', name: zone.name })), address: { '@type': 'PostalAddress', addressLocality: site.city, addressCountry: 'IT' } }; return <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(data).replace(/</g, '\\u003c') }} /> }
